# Generated by Django 2.0 on 2020-08-20 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name='Preço')),
                ('prazo', models.DateField(default=datetime.datetime.today, verbose_name='Prazo')),
                ('data', models.DateField(default=datetime.datetime.today)),
                ('registro', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Observações')),
                ('modeloSTL', models.FileField(blank=True, null=True, upload_to='media/STLFiles', verbose_name='Arquivo STL')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
            },
        ),
    ]
