# Generated by Django 2.0 on 2020-10-03 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oferta', '0002_auto_20200820_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaEnvio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_envio', models.TextField(blank=True, default='', max_length=100, null=True, verbose_name='Forma de Envio')),
            ],
            options={
                'verbose_name': 'Forma de Envio',
                'verbose_name_plural': 'Formas de Envio',
            },
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pagamento', models.TextField(blank=True, default='', max_length=100, null=True, verbose_name='Forma de Pagamento')),
            ],
            options={
                'verbose_name': 'Forma de Pagamento',
                'verbose_name_plural': 'Formas de Pagamento',
            },
        ),
        migrations.AddField(
            model_name='oferta',
            name='aceite',
            field=models.NullBooleanField(verbose_name='Oferta Aceitada'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='forma_envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oferta.FormaEnvio'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='forma_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oferta.FormaPagamento'),
        ),
    ]
