# Generated by Django 2.0 on 2020-08-20 16:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True, max_length=500, null=True, verbose_name='Comentário')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
            },
        ),
        migrations.CreateModel(
            name='EscalaCores',
            fields=[
                ('cor', models.CharField(default='', max_length=5, primary_key=True, serialize=False, verbose_name='Cor')),
            ],
            options={
                'verbose_name': 'Escala de Cor',
                'verbose_name_plural': 'Escala de Cores',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('m', models.CharField(default='', max_length=100, primary_key=True, serialize=False, verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
            },
        ),
        migrations.CreateModel(
            name='Pregao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='', max_length=100, verbose_name='Tipo de serviço')),
                ('dente', multiselectfield.db.fields.MultiSelectField(choices=[('18', '18'), ('17', '17'), ('16', '16'), ('15', '15'), ('14', '14'), ('13', '13'), ('12', '12'), ('11', '11'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('48', '48'), ('47', '47'), ('46', '46'), ('45', '45'), ('44', '44'), ('43', '43'), ('42', '42'), ('41', '41'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38')], default=' ', max_length=100, verbose_name='Dente')),
                ('escala', models.CharField(blank=True, default=' ', max_length=100, null=True, verbose_name='Escala')),
                ('extra', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observações')),
                ('close', models.BooleanField(default=False)),
                ('data', models.DateField(default=datetime.date.today)),
                ('preco', models.DecimalField(decimal_places=2, default='0,00', max_digits=7, verbose_name='Preço')),
                ('prazo', models.DateField(default=datetime.date.today, verbose_name='Prazo')),
                ('modeloSTL', models.FileField(blank=True, null=True, upload_to='STLFiles', verbose_name='Arquivo STL')),
                ('slug_pregao', models.SlugField(unique=True)),
                ('cor', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='pregao.EscalaCores')),
                ('material', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='pregao.Material')),
            ],
            options={
                'verbose_name': 'Pregão',
                'verbose_name_plural': 'Pregões',
            },
        ),
    ]
